# Dengue en Loreto (2000–2024)
## Notebook 03 · Análisis con SQL

**Entrada:** `data/processed/dengue_loreto_limpio.csv`, generado en `02_limpieza.ipynb`.

**Qué hace este notebook:** carga los casos en una base de datos **SQLite** y responde las preguntas del análisis con consultas SQL: cuándo (años), dónde (provincias y distritos) y qué tan graves son los casos.

**Contenido**
1. Creación de la base de datos
2. Consultas básicas: `SELECT`, `COUNT`, `WHERE`
3. Evolución anual: `GROUP BY`
4. Distribución geográfica
5. Gravedad por año: `SUM`, `AVG` y un cambio de clasificación
6. Comparación de periodos: `CASE WHEN`
7. Años epidémicos: `WHERE` frente a `HAVING`

**Resultado:** `data/dengue_loreto.db` (se genera con este notebook y no se sube a GitHub).

---
## 1. Creación de la base de datos

SQLite guarda toda la base de datos en un solo archivo, sin servidor. `to_sql` copia el DataFrame a una tabla llamada `casos`; con `if_exists="replace"`, el notebook se puede ejecutar varias veces sin errores.

In [1]:
import sqlite3
import pandas as pd

casos = pd.read_csv(
    "../data/processed/dengue_loreto_limpio.csv",
    dtype={"ubigeo": str, "diresa": str}
)

# Conectarse a la base de datos (si el archivo no existe, se crea)
conexion = sqlite3.connect("../data/dengue_loreto.db")

# Copiar el DataFrame a una tabla llamada "casos"
casos.to_sql("casos", conexion, if_exists="replace", index=False)
print("Tabla creada")

Tabla creada

In [2]:
def consulta(sql):
    """Ejecuta una consulta SQL y devuelve el resultado como DataFrame."""
    return pd.read_sql(sql, conexion)

---
## 2. Consultas básicas

`SELECT *` trae todas las columnas y `LIMIT` limita el número de filas: es el equivalente de `df.head()`.

In [3]:
consulta("""
SELECT *
FROM casos
LIMIT 5
""")

,provincia,distrito,ubigeo,ano,semana,diresa,edad_anios,grupo_edad,sexo,gravedad,con_alarma_o_grave
0,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,58.0,Adulto (30-59),M,Sin signos de alarma,0
1,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,44.0,Adulto (30-59),F,Sin signos de alarma,0
2,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,21.0,Joven (18-29),F,Sin signos de alarma,0
3,MAYNAS,IQUITOS,160101,2000,1,16,74.0,Adulto mayor (60+),M,Sin signos de alarma,0
4,MAYNAS,IQUITOS,160101,2000,1,16,42.0,Adulto (30-59),F,Sin signos de alarma,0

`COUNT(*)` cuenta filas. Se usa para verificar que la carga fue completa: deben ser 107,074 casos.

In [4]:
consulta("""
SELECT COUNT(*) AS total_casos
FROM casos
""")

   total_casos
0       107074

`WHERE` filtra filas. En SQL se compara con un solo `=` y el texto va entre comillas simples.

In [5]:
consulta("""
SELECT COUNT(*) AS casos_graves_2024
FROM casos
WHERE ano = 2024
    AND gravedad = 'Grave'
""")

   casos_graves_2024
0                 10

---
## 3. Evolución anual

`GROUP BY` agrupa las filas por año y `COUNT(*)` cuenta los casos de cada grupo, como `groupby` en pandas.

In [6]:
consulta("""
SELECT ano, COUNT(*) AS casos
FROM casos
GROUP BY ano
ORDER BY ano
""")

     ano  casos
0   2000    518
1   2001    510
2   2002   2500
3   2003    784
4   2004   2580
5   2005   1772
6   2006   1995
7   2007   1720
8   2008   7232
9   2009   3782
10  2010   1322
11  2011  21245
12  2012   4382
13  2013   4479
14  2014   7049
15  2015   1630
16  2016   1686
17  2017   1089
18  2018   1833
19  2019   2547
20  2020   7800
21  2021   5115
22  2022   8926
23  2023   6582
24  2024   7996

**Hallazgo: Loreto tiene su propia historia epidémica.**

- El año con más casos es **2011 (21,245)**, seguido de 2022 (8,926), 2024 (7,996), 2020 (7,800) y 2008 (7,232).
- A nivel nacional, 2023 y 2024 fueron años récord, pero en Loreto fueron años habituales (**6,582** y **7,996** casos). La ola de 2023–2024 golpeó sobre todo a la costa norte del país.

---
## 4. Distribución geográfica

### 4.1 Casos por provincia

In [7]:
consulta("""
SELECT provincia, COUNT(*) AS casos
FROM casos
GROUP BY provincia
ORDER BY casos DESC;
""")

                 provincia  casos
0                   MAYNAS  71117
1            ALTO AMAZONAS  22135
2                  UCAYALI   3513
3        DATEM DEL MARA�ON   3075
4                  REQUENA   2400
5                   LORETO   2398
6  MARISCAL RAMON CASTILLA   1706
7                 PUTUMAYO    730

> ⚠️ El nombre `DATEM DEL MARA�ON` sigue dañado: la reparación del notebook 01 no encontró una versión limpia de ese nombre. Pendiente: agregarlo al diccionario de correcciones manuales.

### 4.2 Los 10 distritos con más casos

**Regla de SQL:** toda columna del `SELECT` que no esté dentro de una función de agregación (`COUNT`, `SUM`, `AVG`...) debe estar en el `GROUP BY`. SQLite es permisivo con esta regla, pero PostgreSQL, SQL Server y Oracle darían error. Se agrupa por `ubigeo` (el código) y `distrito` (el nombre que se muestra).

In [8]:
consulta("""
SELECT ubigeo, distrito, COUNT(*) AS casos
FROM casos
GROUP BY ubigeo, distrito
ORDER BY casos DESC
LIMIT 10
""")

   ubigeo           distrito  casos
0  160101            IQUITOS  30094
1  160201         YURIMAGUAS  20187
2  160113  SAN JUAN BAUTISTA  16988
3  160108           PUNCHANA  12332
4  160112              BELEN   9790
5  160601          CONTAMANA   2513
6  160701           BARRANCA   2019
7  160301              NAUTA   1561
8  160501            REQUENA   1348
9  160206            LAGUNAS   1269

**Hallazgo: el dengue en Loreto es, sobre todo, un problema urbano de Iquitos.**

- **Maynas concentra el 66.4%** de los casos (71,117) y **Alto Amazonas el 20.7%** (22,135): juntas, casi 9 de cada 10 casos.
- Los cuatro distritos de la ciudad de Iquitos (**Iquitos, San Juan Bautista, Punchana y Belén**) suman **69,204 casos: el 64.6% de Loreto**.
- **Yurimaguas** (20,187 casos) es el segundo distrito con más casos y concentra casi todos los de Alto Amazonas.
- **Precaución:** son conteos absolutos. Para comparar el riesgo entre distritos hace falta la población de cada uno (incidencia).

---
## 5. Gravedad por año

`con_alarma_o_grave` se guardó como 1 (sí) y 0 (no), así que:

- `SUM` cuenta los casos con signos de alarma o graves.
- `AVG` da directamente la **proporción**: el promedio de una columna de unos y ceros es la proporción de unos.

Primero se comprueba que la columna tenga los valores esperados (16,068 con signos de alarma + 554 graves = 16,622).

In [9]:
consulta("""
SELECT con_alarma_o_grave, COUNT(*) AS casos
FROM casos
GROUP BY con_alarma_o_grave
""")

   con_alarma_o_grave  casos
0                   0  90452
1                   1  16622

In [10]:
consulta("""
SELECT
    ano,
    COUNT(*) AS casos,
    SUM(con_alarma_o_grave) AS casos_alarma_o_grave,
    ROUND(AVG(con_alarma_o_grave) * 100, 1) AS pct_alarma_o_grave
FROM casos
GROUP BY ano
ORDER BY ano
""")

     ano  casos  casos_alarma_o_grave  pct_alarma_o_grave
0   2000    518                     0                 0.0
1   2001    510                     1                 0.2
2   2002   2500                     1                 0.0
3   2003    784                     0                 0.0
4   2004   2580                     5                 0.2
5   2005   1772                     4                 0.2
6   2006   1995                     3                 0.2
7   2007   1720                    18                 1.0
8   2008   7232                     7                 0.1
9   2009   3782                     1                 0.0
10  2010   1322                   102                 7.7
11  2011  21245                  2851                13.4
12  2012   4382                   796                18.2
13  2013   4479                  2057                45.9
14  2014   7049                  2493                35.4
15  2015   1630                   537                32.9
16  2016   1686                   596                35.3
17  2017   1089                   277                25.4
18  2018   1833                   633                34.5
19  2019   2547                   618                24.3
20  2020   7800                  1747                22.4
21  2021   5115                   490                 9.6
22  2022   8926                  1431                16.0
23  2023   6582                   941                14.3
24  2024   7996                  1013                12.7

**Hallazgo: un cambio de clasificación en 2010.**

- **Entre 2000 y 2009**, entre el 0.0% y el 1.0% de los casos tiene signos de alarma o es grave. **Desde 2010**, el porcentaje salta a valores de entre 7.7% y 45.9%.
- Un salto tan brusco en un año exacto apunta a un **cambio en cómo se clasifican los casos**, no a un cambio real en la enfermedad. La clasificación actual (*sin signos de alarma, con signos de alarma y grave*) fue propuesta por la OMS en 2009 y adoptada en los años siguientes. Antes se usaban otras categorías, que en este dataset quedaron registradas como "sin signos de alarma".
- **Decisión:** el análisis de gravedad se limita a **2010–2024**.

**Hipótesis: posible sesgo de notificación.** Los años con pocos casos tienen porcentajes altos (2013: 4,479 casos y 45.9%) y el año con más casos tiene uno bajo (2011: 21,245 y 13.4%). En una gran epidemia se registran muchos casos leves, lo que reduce el porcentaje de casos graves; en años tranquilos podrían notificarse sobre todo los casos que llegan a un hospital. Estos datos no permiten confirmarlo.

---
## 6. Comparación de periodos: `CASE WHEN`

`CASE WHEN` crea una categoría nueva dentro de la consulta, como `np.where` en pandas: *"cuando el año es menor que 2010, el periodo es '2000-2009'; en otro caso, '2010-2024'"*.

In [11]:
consulta("""
SELECT
    CASE
        WHEN ano < 2010 THEN '2000-2009'
        ELSE '2010-2024'
    END AS periodo,
    COUNT(*) AS casos,
    SUM(con_alarma_o_grave) AS casos_alarma_o_grave,
    ROUND(AVG(con_alarma_o_grave) * 100, 1) AS pct_alarma_o_grave
FROM casos
GROUP BY periodo
""")

     periodo  casos  casos_alarma_o_grave  pct_alarma_o_grave
0  2000-2009  23393                    40                 0.2
1  2010-2024  83681                 16582                19.8

**Hallazgo:** desde 2010, **el 19.8% de los casos de dengue en Loreto presenta signos de alarma o es grave** (16,582 de 83,681), frente al 0.2% registrado entre 2000 y 2009 con la clasificación anterior.

---
## 7. Años epidémicos: `WHERE` frente a `HAVING`

Los dos filtran, pero en momentos distintos:

- **`WHERE`** filtra **filas**, antes de agrupar.
- **`HAVING`** filtra **grupos**, después de agrupar.

Orden de ejecución de una consulta: `FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT`. Por eso no se puede escribir `WHERE COUNT(*) > 7000`: cuando se ejecuta el `WHERE`, todavía no se ha contado nada.

In [12]:
# Años con más de 7,000 casos
consulta("""
SELECT ano, COUNT(*) AS casos
FROM casos
GROUP BY ano
HAVING COUNT(*) > 7000
ORDER BY ano
""")

    ano  casos
0  2008   7232
1  2011  21245
2  2014   7049
3  2020   7800
4  2022   8926
5  2024   7996

---
## 8. Estacionalidad por semana epidemiológica

¿En qué época del año se contagia más la gente en Loreto? Se analiza la distribución de los casos por **semana epidemiológica** de inicio de síntomas.

Para traducir semanas a meses: **semana ÷ 4.3 ≈ mes** (la semana 13 es fin de marzo, la 26 fin de junio y la 39 fin de setiembre).

### 8.1 Curva epidémica de 2011

Se empieza con un solo año, el de más casos (21,245), para ver la forma de una epidemia: cuándo empieza, cuándo llega a su pico y cuándo baja.

In [13]:
consulta("""
SELECT semana, COUNT(*) AS casos
FROM casos
WHERE ano = 2011
GROUP BY semana
ORDER BY semana
""")

    semana  casos
0        1   1305
1        2   2108
2        3   3079
3        4   2518
4        5   1973
5        6   2661
6        7   1295
7        8   1456
8        9    950
9       10    789
10      11    627
11      12    480
12      13    391
13      14    222
14      15    164
15      16    138
16      17     96
17      18     89
18      19     68
19      20     49
20      21     58
21      22     61
22      23     49
23      24     37
24      25     34
25      26     30
26      27     36
27      28     21
28      29     26
29      30     24
30      31     37
31      32     28
32      33     29
33      34     21
34      35     13
35      36     17
36      37     16
37      38     15
38      39     15
39      40     27
40      41     19
41      42     12
42      43      8
43      44     10
44      45     12
45      46     16
46      47     24
47      48     28
48      49     25
49      50     12
50      51     12
51      52     15

**Hallazgo:** el pico de 2011 fue en la **semana 3** (mediados de enero), con **3,079 casos**. La epidemia se concentró entre las semanas 1 y 8 (enero y febrero) y bajó a menos de 100 casos semanales desde la semana 17 (fines de abril).

Además, la semana 1 ya tenía 1,305 casos: la epidemia **empezó a fines de 2010**. Por eso analizar por año calendario puede partir una misma epidemia en dos.

### 8.2 Por qué no se pueden sumar todos los años

Si se suman los casos de cada semana de los 25 años, los años con más casos dominan el resultado: **2011 concentra el 20% de todos los casos**, así que el patrón "promedio" sería en realidad el patrón de 2011.

La solución es trabajar con **proporciones**: qué porcentaje de los casos de cada año ocurrió en cada semana. Así, todos los años pesan igual, sin importar su tamaño.

### 8.3 Porcentaje de los casos de cada año por semana

Se usan dos herramientas nuevas:

- **CTE (`WITH ... AS`):** una tabla temporal con nombre que solo existe durante la consulta. Permite escribir consultas largas paso a paso, como guardar un resultado intermedio en una variable.
- **Función de ventana (`OVER (PARTITION BY ...)`):** calcula el total de cada año **sin juntar las filas**. Cada fila semanal conserva su detalle y recibe al lado el total de su año. Es el equivalente de `groupby().transform("sum")` en pandas.

Se multiplica por `100.0` (con decimal) para evitar la división entera.

In [14]:
consulta("""
WITH semanal AS (
    SELECT ano, semana, COUNT(*) AS casos
    FROM casos
    GROUP BY ano, semana
)
SELECT
    ano,
    semana,
    casos,
    ROUND(casos * 100.0 / SUM(casos) OVER (PARTITION BY ano), 2) AS pct_del_anio
FROM semanal
ORDER BY ano, semana
""")

       ano  semana  casos  pct_del_anio
0     2000       1     10          1.93
1     2000       2     23          4.44
2     2000       3     23          4.44
3     2000       4     21          4.05
4     2000       5     57         11.00
...    ...     ...    ...           ...
1298  2024      48    427          5.34
1299  2024      49    430          5.38
1300  2024      50    354          4.43
1301  2024      51    318          3.98
1302  2024      52    272          3.40

[1303 rows x 4 columns]

### 8.4 Patrón estacional promedio

Se promedian los porcentajes de cada semana entre todos los años, encadenando una segunda CTE.

**Por qué `SUM(pct) / número de años` y no `AVG(pct)`:** si en algún año una semana tuvo cero casos, esa fila no existe en la tabla y `AVG` la ignoraría, inflando el promedio. Al dividir entre el total de años, las semanas sin casos cuentan como 0.

El número de años se obtiene con una **subconsulta** (`SELECT COUNT(DISTINCT ano) FROM casos`), para no escribirlo a mano.

In [15]:
consulta("""
WITH semanal AS (
    SELECT ano, semana, COUNT(*) AS casos
    FROM casos
    GROUP BY ano, semana
),
proporciones AS (
    SELECT
        ano,
        semana,
        casos * 100.0 / SUM(casos) OVER (PARTITION BY ano) AS pct
    FROM semanal
)
SELECT
    semana,
    ROUND(SUM(pct) / (SELECT COUNT(DISTINCT ano) FROM casos), 2) AS pct_promedio
FROM proporciones
GROUP BY semana
ORDER BY semana
""")

    semana  pct_promedio
0        1          3.11
1        2          3.47
2        3          3.37
3        4          3.51
4        5          3.60
5        6          3.58
6        7          3.12
7        8          2.89
8        9          2.52
9       10          2.70
10      11          2.57
11      12          2.18
12      13          2.07
13      14          2.04
14      15          2.02
15      16          1.93
16      17          1.53
17      18          1.52
18      19          1.48
19      20          1.35
20      21          1.18
21      22          1.21
22      23          1.14
23      24          1.11
24      25          0.91
25      26          1.03
26      27          1.12
27      28          0.93
28      29          0.85
29      30          0.73
30      31          0.89
31      32          0.82
32      33          0.79
33      34          0.86
34      35          0.70
35      36          0.91
36      37          1.13
37      38          1.15
38      39          1.24
39      40          1.10
40      41          1.46
41      42          1.76
42      43          1.74
43      44          1.91
44      45          2.39
45      46          2.80
46      47          2.72
47      48          3.18
48      49          3.18
49      50          2.99
50      51          2.49
51      52          2.59
52      53          0.41

**Validación:** los porcentajes de cada año suman 100%, así que el promedio de todas las semanas también debe sumar 100%.

In [16]:
estacional = consulta("""
WITH semanal AS (
    SELECT ano, semana, COUNT(*) AS casos
    FROM casos
    GROUP BY ano, semana
),
proporciones AS (
    SELECT ano, semana, casos * 100.0 / SUM(casos) OVER (PARTITION BY ano) AS pct
    FROM semanal
)
SELECT semana, SUM(pct) / (SELECT COUNT(DISTINCT ano) FROM casos) AS pct_promedio
FROM proporciones
GROUP BY semana
""")

print(f"Suma de los porcentajes: {estacional['pct_promedio'].sum():.1f}%")

Suma de los porcentajes: 100.0%

---
## 9. Gravedad por grupo de edad

¿Qué grupos de edad tienen un mayor porcentaje de casos con signos de alarma o graves? Se analiza solo el periodo **2010–2024**, por el cambio de clasificación de la gravedad.

**Ordenar categorías con `CASE WHEN`:** los grupos de edad se guardaron como texto, así que SQL los ordenaría alfabéticamente ("Adolescente", "Adulto", "Adulto mayor", "Joven", "Niño"). Para ordenarlos de menor a mayor edad, se asigna a cada grupo un número con `CASE` dentro del `ORDER BY`.

**Precaución:** este porcentaje mide la **gravedad entre quienes se enfermaron**, no el riesgo de enfermarse. Para comparar el riesgo hace falta la población de cada grupo (incidencia).

In [17]:
por_edad = consulta("""
SELECT
    grupo_edad,
    COUNT(*) AS casos,
    SUM(con_alarma_o_grave) AS casos_alarma_o_grave,
    ROUND(AVG(con_alarma_o_grave) * 100, 1) AS pct_alarma_o_grave
FROM casos
WHERE ano >= 2010
GROUP BY grupo_edad
ORDER BY
    CASE grupo_edad
        WHEN 'Niño (0-11)' THEN 1
        WHEN 'Adolescente (12-17)' THEN 2
        WHEN 'Joven (18-29)' THEN 3
        WHEN 'Adulto (30-59)' THEN 4
        WHEN 'Adulto mayor (60+)' THEN 5
    END
""")

print("Casos:", por_edad["casos"].sum())
print("Con alarma o graves:", por_edad["casos_alarma_o_grave"].sum())
por_edad

Casos: 83681
Con alarma o graves: 16582

            grupo_edad  casos  casos_alarma_o_grave  pct_alarma_o_grave
0          Niño (0-11)  22816                  4481                19.6
1  Adolescente (12-17)  14668                  3232                22.0
2        Joven (18-29)  18175                  3789                20.8
3       Adulto (30-59)  23162                  4188                18.1
4   Adulto mayor (60+)   4860                   892                18.4

**Hallazgos**

- **La gravedad es muy similar en todas las edades:** entre el **18.1%** (adultos de 30 a 59 años) y el **22.0%** (adolescentes) de los casos presentan signos de alarma o son graves. En la práctica, cerca de **1 de cada 5 casos** necesita atención especial, en cualquier grupo de edad.
- **Los adolescentes tienen el porcentaje más alto (22.0%)**, y los adultos mayores (18.4%) no están entre los más afectados, a diferencia de lo que ocurre en muchas otras enfermedades.
- Con varios miles de casos por grupo, el margen de error de cada porcentaje es de alrededor de ±1 punto, así que la diferencia entre grupos probablemente no es casual, aunque es pequeña.
- **Precaución:** la gravedad varió mucho entre años (de 7.7% a 45.9%). Si un grupo concentró sus casos en los años con porcentajes altos, su promedio subiría sin que la edad sea la causa.
- **Implicación:** la vigilancia de los signos de alarma debe aplicarse a pacientes de todas las edades, no solo a niños y adultos mayores.

**Hallazgos: la temporada del dengue en Loreto**

- **Temporada alta: de la semana 45 a la 16 (aproximadamente noviembre a mediados de abril).** En esas 24 semanas, menos de la mitad del año, ocurre en promedio el **67.4%** de los casos.
- **El pico está en las semanas 2 a 6 (enero y comienzos de febrero)**, con entre 3.4% y 3.6% de los casos anuales por semana. Hay un segundo máximo en las semanas 48 y 49 (fines de noviembre y comienzos de diciembre).
- **Temporada baja: de la semana 25 a la 40 (aproximadamente julio a setiembre)**, con menos del 1.3% de los casos por semana. El mínimo está en las semanas 30 y 35 (0.7%).
- **El primer trimestre concentra el triple de casos que el tercero:** 38.7% en las semanas 1 a 13 frente a 12.1% en las semanas 27 a 39.
- La semana 53 tiene un porcentaje bajo (0.4%) porque solo existe en algunos años.

**Comparación con el contexto:**

- **Coincide con la temporada nacional** del dengue, que suele ir de noviembre a mayo.
- **No coincide con el pico de calor de Iquitos** (setiembre a noviembre, según el proyecto del índice de calor): los casos empiezan a subir justo al final de esa temporada y llegan a su pico dos o tres meses después. **Hipótesis:** el factor más relacionado podría ser la lluvia, que crea criaderos de mosquitos en agua acumulada. Comprobarlo requeriría datos de precipitación.

---
### 10.1 Datos de población

**Fuente:** *Población identificada con DNI*, RENIEC (Plataforma Nacional de Datos Abiertos). Personas inscritas en el RENIEC con DNI, por lugar de residencia, edad y sexo.

Cada fila es una combinación de distrito, edad, sexo y tipo de DNI, y `CANTIDAD` indica cuántas personas hay en ella. Para obtener la población de un distrito se suma `CANTIDAD`, en lugar de contar filas. El archivo incluye `UBIGEO_INEI`, el mismo sistema de códigos de los casos de dengue.

In [18]:
poblacion_raw = pd.read_csv(
    "../data/raw/16_OPP_2021_SEP.csv",
    sep=";",
    encoding="utf-8-sig",   # quita el BOM del inicio del archivo
    dtype={"UBIGEO_INEI": str, "UBIGEO_RENIEC": str},
    usecols=["Residencia", "UBIGEO_RENIEC", "UBIGEO_INEI", "Distrito", "Edad", "Sexo", "Cantidad"]
)
poblacion_raw["Residencia"].value_counts()

Residencia
Nacional      442534
Extranjero     12264
10                 1
Name: count, dtype: int64

In [19]:
# Solo residentes en el Perú y en Loreto (la fila basura queda fuera con este filtro)
pob_loreto = poblacion_raw[
    (poblacion_raw["Residencia"] == "Nacional")
    & (poblacion_raw["UBIGEO_INEI"].str.startswith("16", na=False))
].copy()

print(f"Personas con DNI en Loreto: {pob_loreto['Cantidad'].sum():,.0f}")
print("Códigos de distrito:", pob_loreto["UBIGEO_RENIEC"].nunique())

Personas con DNI en Loreto: 1,167,201
Códigos de distrito: 55

### 10.2 Población por distrito

In [22]:
pob_distrito = (
    pob_loreto.groupby(["UBIGEO_RENIEC", "UBIGEO_INEI", "Distrito"], as_index=False)["Cantidad"]
    .sum()
    .rename(columns={"Cantidad": "poblacion"})
)
pob_distrito

   UBIGEO_RENIEC UBIGEO_INEI                    Distrito  poblacion
0         150101      160101                     Iquitos   172028.0
1         150102      160102                  Alto Nanay     4822.0
2         150103      160103              Fernando Lores    18773.0
3         150104      160105                Las Amazonas    12509.0
4         150105      160106                       Mazan    18526.0
5         150106      160107                        Napo    18821.0
6         150108      160118              Torres Causana     7864.0
7         150109      160109                   Yaquerana        3.0
8         150110      160110                     Indiana    15182.0
9         150111      160111                    Punchana   101865.0
10        150112      160112                       Belén    80749.0
11        150113      160113           San Juan Bautista   136753.0
12        150201      160201                  Yurimaguas    97223.0
13        150202      160202                 Balsapuerto    23608.0
14        150204      160204                  Cahuapanas        1.0
15        150205      160205                     Jeberos     5678.0
16        150206      160206                     Lagunas    16190.0
17        150210      160210                  Santa Cruz     6116.0
18        150211      160211  Teniente César López Rojas     7714.0
19        150301      160301                       Nauta    39295.0
20        150302      160302                    Parinari     8088.0
21        150303      160303                       Tigre    11068.0
22        150304      160305                    Urarinas    17464.0
23        150305      160304                 Trompeteros    11746.0
24        150401      160501                     Requena    32973.0
25        150402      160502                Alto Tapiche     2533.0
26        150403      160503                      Capelo     3924.0
27        150404      160504           Emilio San Martín     8064.0
28        150405      160505                      Maquia    10038.0
29        150406      160506                    Puinahua     6255.0
30        150407      160507                     Saquena     4583.0
31        150408      160508                      Soplin     1119.0
32        150409      160509                     Tapiche     1567.0
33        150410      160510              Jenaro Herrera     5660.0
34        150411      160511                   Yaquerana     3556.0
35        150501      160601                   Contamana    31435.0
36        150502      160606               Vargas Guerra    10931.0
37        150503      160603               Padre Márquez     7557.0
38        150504      160604               Pampa Hermosa     8315.0
39        150505      160605                    Sarayacu    16791.0
40        150506      160602                    Inahuaya     3506.0
41        150601      160401              Ramón Castilla    28384.0
42        150602      160402                       Pebas    17179.0
43        150603      160403                      Yavarí    18750.0
44        150604      160404                   San Pablo    18807.0
45        150701      160701                    Barranca    20286.0
46        150702      160706                      Andoas    15740.0
47        150703      160702                  Cahuapanas    10786.0
48        150704      160703                  Manseriche    12688.0
49        150705      160704                      Morona    11504.0
50        150706      160705                     Pastaza    10978.0
51        150901      160801                    Putumayo     5594.0
52        150902      160802                Rosa Panduro      576.0
53        150903      160803     Teniente Manuel Clavero     3538.0
54        150904      160804                      Yaguas     1498.0

### 10.3 Validación y corrección de los códigos de distrito

La columna `UBIGEO_INEI` del RENIEC tiene códigos incorrectos en algunos distritos. Se usa en su lugar `UBIGEO_RENIEC` y se traduce al código INEI con una tabla de equivalencias pública ([ubigeo-peru-aumentado](https://github.com/jmcastagnetto/ubigeo-peru-aumentado)).

In [23]:
equivalencias = pd.read_csv(
    "https://raw.githubusercontent.com/jmcastagnetto/ubigeo-peru-aumentado/main/ubigeo_distrito.csv",
    dtype={"inei": str, "reniec": str},
    usecols=["inei", "reniec", "provincia", "distrito"]
)
equivalencias.to_csv("../data/raw/ubigeo_equivalencias.csv", index=False)  # copia local

In [24]:
pob_distrito = pob_distrito.merge(
    equivalencias,
    left_on="UBIGEO_RENIEC",
    right_on="reniec",
    how="left",
    indicator=True
)
pob_distrito["_merge"].value_counts()

_merge
both          53
left_only      2
right_only     0
Name: count, dtype: int64

In [26]:
pob_distrito.head(5)

,UBIGEO_RENIEC,UBIGEO_INEI,Distrito,poblacion,inei,reniec,provincia,distrito,_merge
0,150101,160101,Iquitos,172028.0,160101,150101,MAYNAS,IQUITOS,both
1,150102,160102,Alto Nanay,4822.0,160102,150102,MAYNAS,ALTO NANAY,both
2,150103,160103,Fernando Lores,18773.0,160103,150103,MAYNAS,FERNANDO LORES,both
3,150104,160105,Las Amazonas,12509.0,160105,150104,MAYNAS,LAS AMAZONAS,both
4,150105,160106,Mazan,18526.0,160106,150105,MAYNAS,MAZAN,both

In [27]:
# Distritos sin equivalencia
pob_distrito[pob_distrito["_merge"] == "left_only"]

,UBIGEO_RENIEC,UBIGEO_INEI,Distrito,poblacion,inei,reniec,provincia,distrito,_merge
7,150109,160109,Yaquerana,3.0,NaN,NaN,NaN,NaN,left_only
14,150204,160204,Cahuapanas,1.0,NaN,NaN,NaN,NaN,left_only

In [28]:
# Distritos donde el código INEI del RENIEC no coincide con el oficial
pob_distrito[(pob_distrito["_merge"] == "both") & (pob_distrito["UBIGEO_INEI"] != pob_distrito["inei"])]

,UBIGEO_RENIEC,UBIGEO_INEI,Distrito,poblacion,inei,reniec,provincia,distrito,_merge
6,150108,160118,Torres Causana,7864.0,160110,150108,MAYNAS,TORRES CAUSANA,both
8,150110,160110,Indiana,15182.0,160104,150110,MAYNAS,INDIANA,both
9,150111,160111,Punchana,101865.0,160108,150111,MAYNAS,PUNCHANA,both

In [29]:
# Tabla final: solo los distritos con equivalencia, con el código INEI correcto
poblacion = (
    pob_distrito[pob_distrito["_merge"] == "both"]
    [["inei", "provincia", "distrito", "poblacion"]]
    .rename(columns={"inei": "ubigeo"})
)

print(f"Distritos: {len(poblacion)} | Población: {poblacion['poblacion'].sum():,.0f}")
poblacion.to_sql("poblacion", conexion, if_exists="replace", index=False)

Distritos: 53 | Población: 1,167,197

53

**Hallazgos sobre los datos de población**

- Loreto tiene **1,167,201 personas con DNI** en el registro de setiembre de 2021, alrededor de un 13% más que las estimaciones oficiales de población. El registro puede incluir personas que se mudaron sin actualizar su domicilio y fallecidos aún no dados de baja, por lo que **la incidencia calculada será una estimación conservadora**.
- **La columna `UBIGEO_INEI` del RENIEC tiene códigos incorrectos** en tres distritos: Punchana (160111 en lugar de 160108), Indiana (160110 en lugar de 160104) y Torres Causana (160118 en lugar de 160110). Usarla habría dejado a Punchana sin población y habría cruzado los datos de Indiana y Torres Causana. Se usó `UBIGEO_RENIEC` con una tabla de equivalencias.
- Se descartaron 2 códigos antiguos sin equivalencia actual (4 personas en total).
- Resultado: **53 distritos con 1,167,197 personas**.

---
## Resumen

- Se cargaron **107,074 casos** en una base de datos SQLite y se verificó la carga con `COUNT(*)`.
- **Loreto no siguió la ola nacional de 2023–2024:** su año con más casos fue 2011.
- **Los cuatro distritos de la ciudad de Iquitos concentran el 64.6%** de los casos de Loreto.
- **Cambio de clasificación en 2010:** antes de ese año casi ningún caso figura con signos de alarma, por lo que el análisis de gravedad se limita a 2010–2024. En ese periodo, el **19.8%** de los casos presenta signos de alarma o es grave.
- **Estacionalidad:** el 67.4% de los casos ocurre entre noviembre y mediados de abril, con el pico en enero y febrero, y la temporada baja entre julio y setiembre.

**Conceptos de SQL aplicados:** `SELECT`, `WHERE`, `GROUP BY`, `ORDER BY`, `LIMIT`, `COUNT`, `SUM`, `AVG`, `ROUND`, `CASE WHEN`, `HAVING`, CTE (`WITH`), funciones de ventana (`OVER (PARTITION BY ...)`) y subconsultas.

**Siguiente paso:** comparar con el total nacional, analizar la gravedad por grupo de edad y, más adelante, unir datos de población del INEI con `JOIN`.