In [1]:
import sqlite3
import pandas as pd

casos = pd.read_csv(
    "../data/processed/dengue_loreto_limpio.csv",
    dtype={"ubigeo": str, "diresa": str}
)

# Conectarse a la base de datos (si el archivo no existe, se crea)
conexion = sqlite3.connect("../data/dengue_loreto.db")

# Copiar el DataFrame a una tabla llamada "casos"
casos.to_sql("casos", conexion, if_exists="replace", index=False)
print("Tabla creada")

Tabla creada

In [2]:
def consulta(sql):
    """Ejecuta una consulta SQL y devuelve el resultado como DataFrame."""
    return pd.read_sql(sql, conexion)

In [ ]:
consulta("""
SELECT *
FROM casos
LIMIT 5
""")

,provincia,distrito,ubigeo,ano,semana,diresa,edad_anios,grupo_edad,sexo,gravedad,con_alarma_o_grave
0,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,58.0,Adulto (30-59),M,Sin signos de alarma,0
1,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,44.0,Adulto (30-59),F,Sin signos de alarma,0
2,ALTO AMAZONAS,YURIMAGUAS,160201,2000,1,16,21.0,Joven (18-29),F,Sin signos de alarma,0
3,MAYNAS,IQUITOS,160101,2000,1,16,74.0,Adulto mayor (60+),M,Sin signos de alarma,0
4,MAYNAS,IQUITOS,160101,2000,1,16,42.0,Adulto (30-59),F,Sin signos de alarma,0

In [4]:
consulta("""
SELECT COUNT(*) AS total_casos
FROM casos
""")

   total_casos
0       107074

In [5]:
consulta("""
SELECT COUNT(*) AS casos_graves_2024
FROM casos
WHERE ano = 2024
    AND gravedad = 'Grave'
""")

   casos_graves_2024
0                 10

In [6]:
consulta("""
SELECT ano, COUNT(*) AS casos
FROM casos
GROUP BY ano
ORDER BY ano
""")

     ano  casos
0   2000    518
1   2001    510
2   2002   2500
3   2003    784
4   2004   2580
5   2005   1772
6   2006   1995
7   2007   1720
8   2008   7232
9   2009   3782
10  2010   1322
11  2011  21245
12  2012   4382
13  2013   4479
14  2014   7049
15  2015   1630
16  2016   1686
17  2017   1089
18  2018   1833
19  2019   2547
20  2020   7800
21  2021   5115
22  2022   8926
23  2023   6582
24  2024   7996

In [15]:
consulta("""
SELECT provincia, COUNT(*) AS casos
FROM casos
GROUP BY provincia
ORDER BY casos DESC;
""")

                 provincia  casos
0                   MAYNAS  71117
1            ALTO AMAZONAS  22135
2                  UCAYALI   3513
3        DATEM DEL MARA�ON   3075
4                  REQUENA   2400
5                   LORETO   2398
6  MARISCAL RAMON CASTILLA   1706
7                 PUTUMAYO    730

In [29]:
consulta("""
SELECT ubigeo, distrito, COUNT(*) AS casos
FROM casos
GROUP BY ubigeo, distrito
ORDER BY casos DESC
LIMIT 10
""")

   ubigeo           distrito  casos
0  160101            IQUITOS  30094
1  160201         YURIMAGUAS  20187
2  160113  SAN JUAN BAUTISTA  16988
3  160108           PUNCHANA  12332
4  160112              BELEN   9790
5  160601          CONTAMANA   2513
6  160701           BARRANCA   2019
7  160301              NAUTA   1561
8  160501            REQUENA   1348
9  160206            LAGUNAS   1269

In [34]:
consulta("""
SELECT
    ano,
    COUNT(*) AS casos,
    SUM(con_alarma_o_grave) AS casos_alarma_o_grave,
    ROUND(AVG(con_alarma_o_grave) * 100, 1) AS pct_alarma_o_grave
FROM casos
GROUP BY ano
ORDER BY ano
""")

     ano  casos  casos_alarma_o_grave  pct_alarma_o_grave
0   2000    518                     0                 0.0
1   2001    510                     1                 0.2
2   2002   2500                     1                 0.0
3   2003    784                     0                 0.0
4   2004   2580                     5                 0.2
5   2005   1772                     4                 0.2
6   2006   1995                     3                 0.2
7   2007   1720                    18                 1.0
8   2008   7232                     7                 0.1
9   2009   3782                     1                 0.0
10  2010   1322                   102                 7.7
11  2011  21245                  2851                13.4
12  2012   4382                   796                18.2
13  2013   4479                  2057                45.9
14  2014   7049                  2493                35.4
15  2015   1630                   537                32.9
16  2016   1686                   596                35.3
17  2017   1089                   277                25.4
18  2018   1833                   633                34.5
19  2019   2547                   618                24.3
20  2020   7800                  1747                22.4
21  2021   5115                   490                 9.6
22  2022   8926                  1431                16.0
23  2023   6582                   941                14.3
24  2024   7996                  1013                12.7